export const servicePlans = [
  {
    id: "visa-ticket",
    name: "DUMMY TICKET FOR VISA",
    price: 19,
    currencies: "19 USD | 1200 INR | 70 AED | 16 EUR | 14.50 GBP",
    features: [
      "Flight reservation/ itinerary",
      "Verifiable on airline website",
      "Up to 4 changes allowed",
      "Use for visa application/ proof of return",
    ],
    popular: true,
  },
  {
    id: "ticket-hotel",
    name: "DUMMY TICKET & HOTEL",
    price: 35,
    currencies: "35 USD | 2750 INR | 128 AED | 30 EUR | 26.70 GBP",
    features: [
      "Actual reservation from airline/hotel",
      "Verifiable on airline/hotel website",
      "Accommodation up to one month",
      "Up to 4 changes allowed",
      "Use for visa application/ proof of return",
    ],
    popular: false,
  },
  {
    id: "return-ticket",
    name: "DUMMY RETURN TICKET",
    price: 15,
    currencies: "15 USD | 990 INR | 55 AED | 14 EUR | 12.50 GBP",
    features: [
      "Return ticket for showing in immigration",
      "Verifiable flight reservation with PNR",
      "Can be used to show as proof of return or onward travel in most countries",
    ],
    popular: false,
  },
  {
    id: "ticket-receipt",
    name: "TICKET WITH E-RECEIPT",
    price: 49,
    currencies: "49 USD | 3850 INR | 180 AED | 42 EUR | 37.50 GBP",
    features: [
      "E-ticket included",
      "Official receipt",
      "Enhanced verification",
      "Premium service with priority support",
    ],
    popular: false,
  },
  {
    id: "past-dated",
    name: "PAST DATED TICKETS",
    price: 35,
    currencies: "35 USD | 2750 INR | 128 AED | 30 EUR | 26.70 GBP",
    features: ["Custom dates", "Backdated tickets", "Special requests handled", "Expert support included"],
    popular: false,
  },
  {
    id: "hotel-only",
    name: "HOTEL BOOKING ONLY",
    price: 20,
    currencies: "20 USD | 1570 INR | 73 AED | 17 EUR | 15.30 GBP",
    features: ["Hotel confirmation", "Verifiable booking", "Flexible duration", "Worldwide hotels available"],
    popular: false,
  },
]